name: "Pipeline Selic: Extracao e Dashboard"

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar Extração de Dados
        run: python extract.py

      - name: Gerar Dashboard
        run: python dashboard.py

      - name: Salvar Dados no Repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/ docs/
          git commit -m "Pipeline: Atualizacao $(date +'%Y-%m-%d')" || exit 0
          git push